### ISSUE TITLE
Wrong depth in method info

### ISSUE THREAD

**Issue by denisshaf** [Albertbuh/MyUtils#1]
## Description
Wrong depth values in several method's infos displayed in console.
## How to reproduce 
Call RunFunctionToTrace -> MyMethod -> Aboba, Biboba -> InnerMethod.
## Repeatability
Not always.
## Possible reasons
Some methods take lock in the wrong order.

**Comment by Albertbuh** [comment]
Closing issue #1 with commit d992291cee78e2da9fa05c272089386c9464e0ae
